name: Create PR

on:
  push:
    branches: test-b

jobs:
  PR:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repos
        uses: actions/checkout@v2

      - name: Create PR request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          destination_branch: "main"                      
          pr_title: "Pulling ${GITHUB_REF#refs/heads/} branch into main branch" 
          pr_body: |
            "## This is an automatically created PR 
            
            - It will triggered once codes in **dist folder** from ***Classifai_FrontEnd*** has been pushed.
            - Files & sub-folder in **dist folder** of ***Classifai_FrontEnd*** will be copied into ***classifai's webroots*** "

          pr_reviewer: "fariskamaludin-skymind"                         
          pr_assignee: "fariskamaludin-skymind"                         
          pr_label: "auto-pr"                               
          pr_allow_empty: true                             